export interface AirportInfo {
  name: string;
  city: string;
  timezone: string;
}

export const AIRPORTS: Record<string, AirportInfo> = {
  // ── United States ──────────────────────────────────────────────────────────
  // Northeast / Eastern
  'JFK': { name: 'John F. Kennedy International Airport',        city: 'New York, NY',        timezone: 'America/New_York' },
  'LGA': { name: 'LaGuardia Airport',                            city: 'New York, NY',        timezone: 'America/New_York' },
  'EWR': { name: 'Newark Liberty International Airport',         city: 'Newark, NJ',          timezone: 'America/New_York' },
  'BOS': { name: 'Boston Logan International Airport',           city: 'Boston, MA',          timezone: 'America/New_York' },
  'PHL': { name: 'Philadelphia International Airport',           city: 'Philadelphia, PA',    timezone: 'America/New_York' },
  'PIT': { name: 'Pittsburgh International Airport',             city: 'Pittsburgh, PA',      timezone: 'America/New_York' },
  'BUF': { name: 'Buffalo Niagara International Airport',        city: 'Buffalo, NY',         timezone: 'America/New_York' },
  'ROC': { name: 'Greater Rochester International Airport',      city: 'Rochester, NY',       timezone: 'America/New_York' },
  'SYR': { name: 'Syracuse Hancock International Airport',       city: 'Syracuse, NY',        timezone: 'America/New_York' },
  'ALB': { name: 'Albany International Airport',                 city: 'Albany, NY',          timezone: 'America/New_York' },
  'ISP': { name: 'Long Island MacArthur Airport',                city: 'Islip, NY',           timezone: 'America/New_York' },
  'HPN': { name: 'Westchester County Airport',                   city: 'White Plains, NY',    timezone: 'America/New_York' },
  'BDL': { name: 'Bradley International Airport',                city: 'Windsor Locks, CT',   timezone: 'America/New_York' },
  'PVD': { name: 'T.F. Green Airport',                           city: 'Providence, RI',      timezone: 'America/New_York' },
  // Southeast
  'DCA': { name: 'Ronald Reagan Washington National Airport',    city: 'Washington, DC',      timezone: 'America/New_York' },
  'IAD': { name: 'Washington Dulles International Airport',      city: 'Dulles, VA',          timezone: 'America/New_York' },
  'BWI': { name: 'Baltimore/Washington International Airport',   city: 'Baltimore, MD',       timezone: 'America/New_York' },
  'RIC': { name: 'Richmond International Airport',               city: 'Richmond, VA',        timezone: 'America/New_York' },
  'ORF': { name: 'Norfolk International Airport',                city: 'Norfolk, VA',         timezone: 'America/New_York' },
  'ATL': { name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta, GA',     timezone: 'America/New_York' },
  'CLT': { name: 'Charlotte Douglas International Airport',      city: 'Charlotte, NC',       timezone: 'America/New_York' },
  'RDU': { name: 'Raleigh-Durham International Airport',         city: 'Raleigh, NC',         timezone: 'America/New_York' },
  'GSO': { name: 'Piedmont Triad International Airport',         city: 'Greensboro, NC',      timezone: 'America/New_York' },
  'GSP': { name: 'Greenville-Spartanburg International Airport', city: 'Greer, SC',           timezone: 'America/New_York' },
  'CAE': { name: 'Columbia Metropolitan Airport',                city: 'Columbia, SC',        timezone: 'America/New_York' },
  'CHS': { name: 'Charleston International Airport',             city: 'Charleston, SC',      timezone: 'America/New_York' },
  'SAV': { name: 'Savannah/Hilton Head International Airport',   city: 'Savannah, GA',        timezone: 'America/New_York' },
  'JAX': { name: 'Jacksonville International Airport',           city: 'Jacksonville, FL',    timezone: 'America/New_York' },
  'MIA': { name: 'Miami International Airport',                  city: 'Miami, FL',           timezone: 'America/New_York' },
  'FLL': { name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale, FL', timezone: 'America/New_York' },
  'PBI': { name: 'Palm Beach International Airport',             city: 'West Palm Beach, FL', timezone: 'America/New_York' },
  'MCO': { name: 'Orlando International Airport',                city: 'Orlando, FL',         timezone: 'America/New_York' },
  'TPA': { name: 'Tampa International Airport',                  city: 'Tampa, FL',           timezone: 'America/New_York' },
  'RSW': { name: 'Southwest Florida International Airport',      city: 'Fort Myers, FL',      timezone: 'America/New_York' },
  'EYW': { name: 'Key West International Airport',               city: 'Key West, FL',        timezone: 'America/New_York' },
  'TLH': { name: 'Tallahassee International Airport',            city: 'Tallahassee, FL',     timezone: 'America/New_York' },
  'SDF': { name: 'Louisville Muhammad Ali International Airport', city: 'Louisville, KY',     timezone: 'America/New_York' },
  'CVG': { name: 'Cincinnati/Northern Kentucky International Airport', city: 'Cincinnati, OH', timezone: 'America/New_York' },
  'CMH': { name: 'John Glenn Columbus International Airport',    city: 'Columbus, OH',        timezone: 'America/New_York' },
  'CLE': { name: 'Cleveland Hopkins International Airport',      city: 'Cleveland, OH',       timezone: 'America/New_York' },
  'CAK': { name: 'Akron-Canton Airport',                         city: 'Akron, OH',           timezone: 'America/New_York' },
  'DAY': { name: 'Dayton International Airport',                 city: 'Dayton, OH',          timezone: 'America/New_York' },
  'DTW': { name: 'Detroit Metropolitan Wayne County Airport',    city: 'Detroit, MI',         timezone: 'America/New_York' },
  'IND': { name: 'Indianapolis International Airport',           city: 'Indianapolis, IN',    timezone: 'America/New_York' },
  'AVL': { name: 'Asheville Regional Airport',                   city: 'Asheville, NC',       timezone: 'America/New_York' },
  'CHA': { name: 'Chattanooga Metropolitan Airport',             city: 'Chattanooga, TN',     timezone: 'America/New_York' },
  'TYS': { name: 'McGhee Tyson Airport',                         city: 'Knoxville, TN',       timezone: 'America/New_York' },
  'MYR': { name: 'Myrtle Beach International Airport',           city: 'Myrtle Beach, SC',    timezone: 'America/New_York' },
  'GRR': { name: 'Gerald R. Ford International Airport',         city: 'Grand Rapids, MI',    timezone: 'America/New_York' },
  'LAN': { name: 'Capital Region International Airport',         city: 'Lansing, MI',         timezone: 'America/New_York' },
  'FNT': { name: 'Flint Bishop International Airport',           city: 'Flint, MI',           timezone: 'America/New_York' },
  'TVC': { name: 'Cherry Capital Airport',                       city: 'Traverse City, MI',   timezone: 'America/New_York' },
  'AZO': { name: 'Kalamazoo/Battle Creek International Airport', city: 'Kalamazoo, MI',       timezone: 'America/New_York' },
  // Midwest
  'ORD': { name: "O'Hare International Airport",                 city: 'Chicago, IL',         timezone: 'America/Chicago' },
  'MDW': { name: 'Chicago Midway International Airport',         city: 'Chicago, IL',         timezone: 'America/Chicago' },
  'DFW': { name: 'Dallas/Fort Worth International Airport',      city: 'Dallas, TX',          timezone: 'America/Chicago' },
  'IAH': { name: 'George Bush Intercontinental Airport',         city: 'Houston, TX',         timezone: 'America/Chicago' },
  'HOU': { name: 'William P. Hobby Airport',                     city: 'Houston, TX',         timezone: 'America/Chicago' },
  'MSP': { name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis, MN',     timezone: 'America/Chicago' },
  'STL': { name: 'St. Louis Lambert International Airport',      city: 'St. Louis, MO',       timezone: 'America/Chicago' },
  'MCI': { name: 'Kansas City International Airport',            city: 'Kansas City, MO',     timezone: 'America/Chicago' },
  'MSY': { name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans, LA', timezone: 'America/Chicago' },
  'MKE': { name: 'Milwaukee Mitchell International Airport',     city: 'Milwaukee, WI',       timezone: 'America/Chicago' },
  'OMA': { name: 'Eppley Airfield',                              city: 'Omaha, NE',           timezone: 'America/Chicago' },
  'DSM': { name: 'Des Moines International Airport',             city: 'Des Moines, IA',      timezone: 'America/Chicago' },
  'AUS': { name: 'Austin-Bergstrom International Airport',       city: 'Austin, TX',          timezone: 'America/Chicago' },
  'BNA': { name: 'Nashville International Airport',              city: 'Nashville, TN',       timezone: 'America/Chicago' },
  'DAL': { name: 'Dallas Love Field',                            city: 'Dallas, TX',          timezone: 'America/Chicago' },
  'SAT': { name: 'San Antonio International Airport',            city: 'San Antonio, TX',     timezone: 'America/Chicago' },
  'MEM': { name: 'Memphis International Airport',                city: 'Memphis, TN',         timezone: 'America/Chicago' },
  'MSN': { name: 'Dane County Regional Airport',                 city: 'Madison, WI',         timezone: 'America/Chicago' },
  'GRB': { name: 'Green Bay Austin Straubel International Airport', city: 'Green Bay, WI',    timezone: 'America/Chicago' },
  'CID': { name: 'The Eastern Iowa Airport',                     city: 'Cedar Rapids, IA',    timezone: 'America/Chicago' },
  'MLI': { name: 'Quad City International Airport',              city: 'Moline, IL',          timezone: 'America/Chicago' },
  'FSD': { name: 'Sioux Falls Regional Airport',                 city: 'Sioux Falls, SD',     timezone: 'America/Chicago' },
  'FAR': { name: 'Hector International Airport',                 city: 'Fargo, ND',           timezone: 'America/Chicago' },
  'BIS': { name: 'Bismarck Municipal Airport',                   city: 'Bismarck, ND',        timezone: 'America/Chicago' },
  'LNK': { name: 'Lincoln Airport',                              city: 'Lincoln, NE',         timezone: 'America/Chicago' },
  'ICT': { name: 'Wichita Dwight D. Eisenhower National Airport', city: 'Wichita, KS',        timezone: 'America/Chicago' },
  'TUL': { name: 'Tulsa International Airport',                  city: 'Tulsa, OK',           timezone: 'America/Chicago' },
  'OKC': { name: 'Will Rogers World Airport',                    city: 'Oklahoma City, OK',   timezone: 'America/Chicago' },
  'LIT': { name: 'Bill and Hillary Clinton National Airport',    city: 'Little Rock, AR',     timezone: 'America/Chicago' },
  'XNA': { name: 'Northwest Arkansas National Airport',          city: 'Bentonville, AR',     timezone: 'America/Chicago' },
  'SHV': { name: 'Shreveport Regional Airport',                  city: 'Shreveport, LA',      timezone: 'America/Chicago' },
  'BTR': { name: 'Baton Rouge Metropolitan Airport',             city: 'Baton Rouge, LA',     timezone: 'America/Chicago' },
  'ELP': { name: 'El Paso International Airport',                city: 'El Paso, TX',         timezone: 'America/Chicago' },
  'MAF': { name: 'Midland International Air & Space Port',       city: 'Midland, TX',         timezone: 'America/Chicago' },
  'LBB': { name: 'Lubbock Preston Smith International Airport',  city: 'Lubbock, TX',         timezone: 'America/Chicago' },
  'AMA': { name: 'Rick Husband Amarillo International Airport',  city: 'Amarillo, TX',        timezone: 'America/Chicago' },
  'PNS': { name: 'Pensacola International Airport',              city: 'Pensacola, FL',       timezone: 'America/Chicago' },
  'MOB': { name: 'Mobile Regional Airport',                      city: 'Mobile, AL',          timezone: 'America/Chicago' },
  'BHM': { name: 'Birmingham-Shuttlesworth International Airport', city: 'Birmingham, AL',    timezone: 'America/Chicago' },
  'HSV': { name: 'Huntsville International Airport',             city: 'Huntsville, AL',      timezone: 'America/Chicago' },
  'EVV': { name: 'Evansville Regional Airport',                  city: 'Evansville, IN',      timezone: 'America/Chicago' },
  'SBN': { name: 'South Bend International Airport',             city: 'South Bend, IN',      timezone: 'America/Chicago' },
  'FWA': { name: 'Fort Wayne International Airport',             city: 'Fort Wayne, IN',      timezone: 'America/Chicago' },
  // Mountain
  'DEN': { name: 'Denver International Airport',                 city: 'Denver, CO',          timezone: 'America/Denver' },
  'SLC': { name: 'Salt Lake City International Airport',         city: 'Salt Lake City, UT',  timezone: 'America/Denver' },
  'ABQ': { name: 'Albuquerque International Sunport',            city: 'Albuquerque, NM',     timezone: 'America/Denver' },
  'BOI': { name: 'Boise Airport',                                city: 'Boise, ID',           timezone: 'America/Denver' },
  'BIL': { name: 'Billings Logan International Airport',         city: 'Billings, MT',        timezone: 'America/Denver' },
  'GTF': { name: 'Great Falls International Airport',            city: 'Great Falls, MT',     timezone: 'America/Denver' },
  'MSO': { name: 'Missoula Montana Airport',                     city: 'Missoula, MT',        timezone: 'America/Denver' },
  'JAC': { name: 'Jackson Hole Airport',                         city: 'Jackson, WY',         timezone: 'America/Denver' },
  'CPR': { name: 'Casper/Natrona County International Airport',  city: 'Casper, WY',          timezone: 'America/Denver' },
  'RAP': { name: 'Rapid City Regional Airport',                  city: 'Rapid City, SD',      timezone: 'America/Denver' },
  'PIH': { name: 'Pocatello Regional Airport',                   city: 'Pocatello, ID',       timezone: 'America/Denver' },
  'SUN': { name: 'Friedman Memorial Airport',                    city: 'Hailey, ID',          timezone: 'America/Denver' },
  // Arizona (no DST)
  'PHX': { name: 'Phoenix Sky Harbor International Airport',     city: 'Phoenix, AZ',         timezone: 'America/Phoenix' },
  'TUS': { name: 'Tucson International Airport',                 city: 'Tucson, AZ',          timezone: 'America/Phoenix' },
  // Pacific
  'LAX': { name: 'Los Angeles International Airport',            city: 'Los Angeles, CA',     timezone: 'America/Los_Angeles' },
  'SFO': { name: 'San Francisco International Airport',          city: 'San Francisco, CA',   timezone: 'America/Los_Angeles' },
  'SAN': { name: 'San Diego International Airport',              city: 'San Diego, CA',       timezone: 'America/Los_Angeles' },
  'SJC': { name: 'Norman Y. Mineta San José International Airport', city: 'San Jose, CA',     timezone: 'America/Los_Angeles' },
  'OAK': { name: 'Oakland Metropolitan International Airport',   city: 'Oakland, CA',         timezone: 'America/Los_Angeles' },
  'SMF': { name: 'Sacramento International Airport',             city: 'Sacramento, CA',      timezone: 'America/Los_Angeles' },
  'SNA': { name: 'John Wayne Airport',                           city: 'Santa Ana, CA',       timezone: 'America/Los_Angeles' },
  'BUR': { name: 'Hollywood Burbank Airport',                    city: 'Burbank, CA',         timezone: 'America/Los_Angeles' },
  'LGB': { name: 'Long Beach Airport',                           city: 'Long Beach, CA',      timezone: 'America/Los_Angeles' },
  'ONT': { name: 'Ontario International Airport',                city: 'Ontario, CA',         timezone: 'America/Los_Angeles' },
  'PSP': { name: 'Palm Springs International Airport',           city: 'Palm Springs, CA',    timezone: 'America/Los_Angeles' },
  'FAT': { name: 'Fresno Yosemite International Airport',        city: 'Fresno, CA',          timezone: 'America/Los_Angeles' },
  'SBA': { name: 'Santa Barbara Airport',                        city: 'Santa Barbara, CA',   timezone: 'America/Los_Angeles' },
  'MRY': { name: 'Monterey Regional Airport',                    city: 'Monterey, CA',        timezone: 'America/Los_Angeles' },
  'RNO': { name: 'Reno-Tahoe International Airport',             city: 'Reno, NV',            timezone: 'America/Los_Angeles' },
  'LAS': { name: 'Harry Reid International Airport',             city: 'Las Vegas, NV',       timezone: 'America/Los_Angeles' },
  'SEA': { name: 'Seattle-Tacoma International Airport',         city: 'Seattle, WA',         timezone: 'America/Los_Angeles' },
  'PDX': { name: 'Portland International Airport',               city: 'Portland, OR',        timezone: 'America/Los_Angeles' },
  'GEG': { name: 'Spokane International Airport',                city: 'Spokane, WA',         timezone: 'America/Los_Angeles' },
  'EUG': { name: 'Eugene Airport',                               city: 'Eugene, OR',          timezone: 'America/Los_Angeles' },
  'MFR': { name: 'Rogue Valley International-Medford Airport',   city: 'Medford, OR',         timezone: 'America/Los_Angeles' },
  'RDM': { name: 'Redmond Airport',                              city: 'Redmond, OR',         timezone: 'America/Los_Angeles' },
  'BFL': { name: 'Meadows Field Airport',                        city: 'Bakersfield, CA',     timezone: 'America/Los_Angeles' },
  // Alaska / Hawaii
  'ANC': { name: 'Ted Stevens Anchorage International Airport',  city: 'Anchorage, AK',       timezone: 'America/Anchorage' },
  'FAI': { name: 'Fairbanks International Airport',              city: 'Fairbanks, AK',       timezone: 'America/Anchorage' },
  'HNL': { name: 'Daniel K. Inouye International Airport',       city: 'Honolulu, HI',        timezone: 'Pacific/Honolulu' },
  'OGG': { name: 'Kahului Airport',                              city: 'Kahului, HI',         timezone: 'Pacific/Honolulu' },
  'KOA': { name: 'Ellison Onizuka Kona International Airport',   city: 'Kailua-Kona, HI',     timezone: 'Pacific/Honolulu' },
  'LIH': { name: 'Lihue Airport',                                city: 'Lihue, HI',           timezone: 'Pacific/Honolulu' },
  // Puerto Rico
  'SJU': { name: 'Luis Muñoz Marín International Airport',       city: 'San Juan, PR',        timezone: 'America/Puerto_Rico' },
  'BQN': { name: 'Rafael Hernández Airport',                     city: 'Aguadilla, PR',       timezone: 'America/Puerto_Rico' },
  // ── Canada ──────────────────────────────────────────────────────────────────
  'YYZ': { name: 'Toronto Pearson International Airport',        city: 'Toronto, ON',         timezone: 'America/Toronto' },
  'YOW': { name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa, ON',         timezone: 'America/Toronto' },
  'YUL': { name: 'Montréal-Trudeau International Airport',       city: 'Montreal, QC',        timezone: 'America/Montreal' },
  'YQB': { name: 'Québec City Jean Lesage International Airport', city: 'Quebec City, QC',    timezone: 'America/Montreal' },
  'YHZ': { name: 'Halifax Stanfield International Airport',      city: 'Halifax, NS',         timezone: 'America/Halifax' },
  'YVR': { name: 'Vancouver International Airport',              city: 'Vancouver, BC',       timezone: 'America/Vancouver' },
  'YYC': { name: 'Calgary International Airport',                city: 'Calgary, AB',         timezone: 'America/Edmonton' },
  'YEG': { name: 'Edmonton International Airport',               city: 'Edmonton, AB',        timezone: 'America/Edmonton' },
  'YWG': { name: 'Winnipeg James Armstrong Richardson International Airport', city: 'Winnipeg, MB', timezone: 'America/Winnipeg' },
  // ── Mexico ──────────────────────────────────────────────────────────────────
  'MEX': { name: 'Mexico City International Airport',            city: 'Mexico City, MX',     timezone: 'America/Mexico_City' },
  'CUN': { name: 'Cancún International Airport',                 city: 'Cancún, MX',          timezone: 'America/Mexico_City' },
  'GDL': { name: 'Guadalajara International Airport',            city: 'Guadalajara, MX',     timezone: 'America/Mexico_City' },
  'MTY': { name: 'Monterrey International Airport',              city: 'Monterrey, MX',       timezone: 'America/Mexico_City' },
  'PVR': { name: 'Licenciado Gustavo Díaz Ordaz International Airport', city: 'Puerto Vallarta, MX', timezone: 'America/Mexico_City' },
  'SJD': { name: 'Los Cabos International Airport',              city: 'San José del Cabo, MX', timezone: 'America/Mexico_City' },
  // ── Caribbean ───────────────────────────────────────────────────────────────
  'SDQ': { name: 'Las Américas International Airport',           city: 'Santo Domingo, DO',   timezone: 'America/Santo_Domingo' },
  'PUJ': { name: 'Punta Cana International Airport',             city: 'Punta Cana, DO',      timezone: 'America/Santo_Domingo' },
  'MBJ': { name: 'Sangster International Airport',               city: 'Montego Bay, JM',     timezone: 'America/Jamaica' },
  'KIN': { name: 'Norman Manley International Airport',          city: 'Kingston, JM',        timezone: 'America/Jamaica' },
  'NAS': { name: 'Lynden Pindling International Airport',        city: 'Nassau, BS',          timezone: 'America/Nassau' },
  'GCM': { name: 'Owen Roberts International Airport',           city: 'Grand Cayman, KY',    timezone: 'America/Cayman' },
  'POS': { name: 'Piarco International Airport',                 city: 'Port of Spain, TT',   timezone: 'America/Port_of_Spain' },
  'BGI': { name: 'Grantley Adams International Airport',         city: 'Bridgetown, BB',      timezone: 'America/Barbados' },
  'SXM': { name: 'Princess Juliana International Airport',       city: 'Sint Maarten, SX',    timezone: 'America/Curacao' },
  'BDA': { name: 'L.F. Wade International Airport',              city: 'Bermuda',             timezone: 'Atlantic/Bermuda' },
  // ── Europe ──────────────────────────────────────────────────────────────────
  'LHR': { name: 'London Heathrow Airport',                      city: 'London, UK',          timezone: 'Europe/London' },
  'LGW': { name: 'London Gatwick Airport',                       city: 'London, UK',          timezone: 'Europe/London' },
  'STN': { name: 'London Stansted Airport',                      city: 'London, UK',          timezone: 'Europe/London' },
  'LTN': { name: 'London Luton Airport',                         city: 'London, UK',          timezone: 'Europe/London' },
  'MAN': { name: 'Manchester Airport',                           city: 'Manchester, UK',      timezone: 'Europe/London' },
  'BHX': { name: 'Birmingham Airport',                           city: 'Birmingham, UK',      timezone: 'Europe/London' },
  'EDI': { name: 'Edinburgh Airport',                            city: 'Edinburgh, UK',       timezone: 'Europe/London' },
  'GLA': { name: 'Glasgow Airport',                              city: 'Glasgow, UK',         timezone: 'Europe/London' },
  'DUB': { name: 'Dublin Airport',                               city: 'Dublin, IE',          timezone: 'Europe/Dublin' },
  'CDG': { name: 'Charles de Gaulle Airport',                    city: 'Paris, FR',           timezone: 'Europe/Paris' },
  'ORY': { name: 'Paris Orly Airport',                           city: 'Paris, FR',           timezone: 'Europe/Paris' },
  'NCE': { name: 'Nice Côte d\'Azur Airport',                    city: 'Nice, FR',            timezone: 'Europe/Paris' },
  'FRA': { name: 'Frankfurt Airport',                            city: 'Frankfurt, DE',       timezone: 'Europe/Berlin' },
  'MUC': { name: 'Munich Airport',                               city: 'Munich, DE',          timezone: 'Europe/Berlin' },
  'DUS': { name: 'Düsseldorf Airport',                           city: 'Düsseldorf, DE',      timezone: 'Europe/Berlin' },
  'HAM': { name: 'Hamburg Airport',                              city: 'Hamburg, DE',         timezone: 'Europe/Berlin' },
  'BER': { name: 'Berlin Brandenburg Airport',                   city: 'Berlin, DE',          timezone: 'Europe/Berlin' },
  'AMS': { name: 'Amsterdam Airport Schiphol',                   city: 'Amsterdam, NL',       timezone: 'Europe/Amsterdam' },
  'BRU': { name: 'Brussels Airport',                             city: 'Brussels, BE',        timezone: 'Europe/Brussels' },
  'ZRH': { name: 'Zurich Airport',                               city: 'Zurich, CH',          timezone: 'Europe/Zurich' },
  'GVA': { name: 'Geneva Airport',                               city: 'Geneva, CH',          timezone: 'Europe/Zurich' },
  'VIE': { name: 'Vienna International Airport',                 city: 'Vienna, AT',          timezone: 'Europe/Vienna' },
  'MXP': { name: 'Milan Malpensa Airport',                       city: 'Milan, IT',           timezone: 'Europe/Rome' },
  'FCO': { name: 'Leonardo da Vinci International Airport',      city: 'Rome, IT',            timezone: 'Europe/Rome' },
  'VCE': { name: 'Venice Marco Polo Airport',                    city: 'Venice, IT',          timezone: 'Europe/Rome' },
  'NAP': { name: 'Naples International Airport',                 city: 'Naples, IT',          timezone: 'Europe/Rome' },
  'MAD': { name: 'Adolfo Suárez Madrid-Barajas Airport',         city: 'Madrid, ES',          timezone: 'Europe/Madrid' },
  'BCN': { name: 'Barcelona El Prat Airport',                    city: 'Barcelona, ES',       timezone: 'Europe/Madrid' },
  'LIS': { name: 'Humberto Delgado Airport',                     city: 'Lisbon, PT',          timezone: 'Europe/Lisbon' },
  'CPH': { name: 'Copenhagen Airport',                           city: 'Copenhagen, DK',      timezone: 'Europe/Copenhagen' },
  'ARN': { name: 'Stockholm Arlanda Airport',                    city: 'Stockholm, SE',       timezone: 'Europe/Stockholm' },
  'OSL': { name: 'Oslo Gardermoen Airport',                      city: 'Oslo, NO',            timezone: 'Europe/Oslo' },
  'HEL': { name: 'Helsinki-Vantaa Airport',                      city: 'Helsinki, FI',        timezone: 'Europe/Helsinki' },
  'SVO': { name: 'Sheremetyevo International Airport',           city: 'Moscow, RU',          timezone: 'Europe/Moscow' },
  'WAW': { name: 'Warsaw Chopin Airport',                        city: 'Warsaw, PL',          timezone: 'Europe/Warsaw' },
  'PRG': { name: 'Václav Havel Airport Prague',                  city: 'Prague, CZ',          timezone: 'Europe/Prague' },
  'BUD': { name: 'Budapest Ferenc Liszt International Airport',  city: 'Budapest, HU',        timezone: 'Europe/Budapest' },
  'ATH': { name: 'Athens International Airport',                 city: 'Athens, GR',          timezone: 'Europe/Athens' },
  'IST': { name: 'Istanbul Airport',                             city: 'Istanbul, TR',        timezone: 'Europe/Istanbul' },
  'OTP': { name: 'Henri Coandă International Airport',           city: 'Bucharest, RO',       timezone: 'Europe/Bucharest' },
  // ── Asia ────────────────────────────────────────────────────────────────────
  'NRT': { name: 'Narita International Airport',                 city: 'Tokyo, JP',           timezone: 'Asia/Tokyo' },
  'HND': { name: 'Tokyo Haneda Airport',                         city: 'Tokyo, JP',           timezone: 'Asia/Tokyo' },
  'KIX': { name: 'Kansai International Airport',                 city: 'Osaka, JP',           timezone: 'Asia/Tokyo' },
  'ICN': { name: 'Incheon International Airport',                city: 'Seoul, KR',           timezone: 'Asia/Seoul' },
  'PEK': { name: 'Beijing Capital International Airport',        city: 'Beijing, CN',         timezone: 'Asia/Shanghai' },
  'PVG': { name: 'Shanghai Pudong International Airport',        city: 'Shanghai, CN',        timezone: 'Asia/Shanghai' },
  'CAN': { name: 'Guangzhou Baiyun International Airport',       city: 'Guangzhou, CN',       timezone: 'Asia/Shanghai' },
  'HKG': { name: 'Hong Kong International Airport',              city: 'Hong Kong',           timezone: 'Asia/Hong_Kong' },
  'TPE': { name: 'Taiwan Taoyuan International Airport',         city: 'Taipei, TW',          timezone: 'Asia/Taipei' },
  'MNL': { name: 'Ninoy Aquino International Airport',           city: 'Manila, PH',          timezone: 'Asia/Manila' },
  'SGN': { name: 'Tan Son Nhat International Airport',           city: 'Ho Chi Minh City, VN', timezone: 'Asia/Ho_Chi_Minh' },
  'HAN': { name: 'Noi Bai International Airport',                city: 'Hanoi, VN',           timezone: 'Asia/Ho_Chi_Minh' },
  'DEL': { name: 'Indira Gandhi International Airport',          city: 'New Delhi, IN',       timezone: 'Asia/Kolkata' },
  'BOM': { name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai, IN',      timezone: 'Asia/Kolkata' },
  'BLR': { name: 'Kempegowda International Airport',             city: 'Bangalore, IN',       timezone: 'Asia/Kolkata' },
  'DXB': { name: 'Dubai International Airport',                  city: 'Dubai, AE',           timezone: 'Asia/Dubai' },
  'AUH': { name: 'Abu Dhabi International Airport',              city: 'Abu Dhabi, AE',       timezone: 'Asia/Dubai' },
  'DOH': { name: 'Hamad International Airport',                  city: 'Doha, QA',            timezone: 'Asia/Qatar' },
  'SIN': { name: 'Singapore Changi Airport',                     city: 'Singapore',           timezone: 'Asia/Singapore' },
  'BKK': { name: 'Suvarnabhumi Airport',                         city: 'Bangkok, TH',         timezone: 'Asia/Bangkok' },
  'KUL': { name: 'Kuala Lumpur International Airport',           city: 'Kuala Lumpur, MY',    timezone: 'Asia/Kuala_Lumpur' },
  'CGK': { name: 'Soekarno-Hatta International Airport',         city: 'Jakarta, ID',         timezone: 'Asia/Jakarta' },
  // ── Oceania ─────────────────────────────────────────────────────────────────
  'SYD': { name: 'Sydney Kingsford Smith Airport',               city: 'Sydney, AU',          timezone: 'Australia/Sydney' },
  'MEL': { name: 'Melbourne Airport',                            city: 'Melbourne, AU',       timezone: 'Australia/Melbourne' },
  'BNE': { name: 'Brisbane Airport',                             city: 'Brisbane, AU',        timezone: 'Australia/Brisbane' },
  'PER': { name: 'Perth Airport',                                city: 'Perth, AU',           timezone: 'Australia/Perth' },
  'ADL': { name: 'Adelaide Airport',                             city: 'Adelaide, AU',        timezone: 'Australia/Adelaide' },
  'AKL': { name: 'Auckland Airport',                             city: 'Auckland, NZ',        timezone: 'Pacific/Auckland' },
  'CHC': { name: 'Christchurch Airport',                         city: 'Christchurch, NZ',    timezone: 'Pacific/Auckland' },
  // ── Africa ──────────────────────────────────────────────────────────────────
  'JNB': { name: 'O.R. Tambo International Airport',             city: 'Johannesburg, ZA',    timezone: 'Africa/Johannesburg' },
  'CPT': { name: 'Cape Town International Airport',              city: 'Cape Town, ZA',       timezone: 'Africa/Johannesburg' },
  'NBO': { name: 'Jomo Kenyatta International Airport',          city: 'Nairobi, KE',         timezone: 'Africa/Nairobi' },
  'CAI': { name: 'Cairo International Airport',                  city: 'Cairo, EG',           timezone: 'Africa/Cairo' },
  'CMN': { name: 'Mohammed V International Airport',             city: 'Casablanca, MA',      timezone: 'Africa/Casablanca' },
  'LOS': { name: 'Murtala Muhammed International Airport',       city: 'Lagos, NG',           timezone: 'Africa/Lagos' },
  // ── South America ───────────────────────────────────────────────────────────
  'GRU': { name: 'São Paulo/Guarulhos International Airport',    city: 'São Paulo, BR',       timezone: 'America/Sao_Paulo' },
  'GIG': { name: 'Rio de Janeiro/Galeão International Airport',  city: 'Rio de Janeiro, BR',  timezone: 'America/Sao_Paulo' },
  'EZE': { name: 'Ministro Pistarini International Airport',     city: 'Buenos Aires, AR',    timezone: 'America/Argentina/Buenos_Aires' },
  'SCL': { name: 'Arturo Merino Benítez International Airport',  city: 'Santiago, CL',        timezone: 'America/Santiago' },
  'LIM': { name: 'Jorge Chávez International Airport',           city: 'Lima, PE',            timezone: 'America/Lima' },
  'BOG': { name: 'El Dorado International Airport',              city: 'Bogotá, CO',          timezone: 'America/Bogota' },
  'UIO': { name: 'Mariscal Sucre International Airport',         city: 'Quito, EC',           timezone: 'America/Quito' },
};

export const getAirportTimezone = (iata: string): string =>
  AIRPORTS[iata.toUpperCase()]?.timezone ?? 'America/Chicago';

export const getAirportAddress = (iata: string): string => {
  const info = AIRPORTS[iata.toUpperCase()];
  return info ? `${info.name}, ${info.city}` : `${iata} Airport`;
};

export const getAirportLabel = (iata: string): string => {
  const info = AIRPORTS[iata.toUpperCase()];
  return info ? `${iata} – ${info.city}` : iata;
};
